/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazddsi;

import javax.swing.JOptionPane;

/**
 *
 * @author alonso
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        this.setTitle("Menú principal del sistema"); 
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        subsis1 = new javax.swing.JButton();
        subsis2 = new javax.swing.JButton();
        subsis3 = new javax.swing.JButton();
        subsis4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        botonTerminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        subsis1.setText("Funcionalidad 1");
        subsis1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subsis1ActionPerformed(evt);
            }
        });

        subsis2.setText("Funcionalidad 2");
        subsis2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subsis2ActionPerformed(evt);
            }
        });

        subsis3.setText("Funcionalidad 3");
        subsis3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subsis3ActionPerformed(evt);
            }
        });

        subsis4.setText("Funcionalidad 4");
        subsis4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subsis4ActionPerformed(evt);
            }
        });

        jLabel1.setText("PROYECTO: CAMPAMENTO DE TENIS");

        botonTerminar.setText("SALIR");
        botonTerminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTerminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(subsis1)
                    .addComponent(subsis3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(subsis2)
                    .addComponent(subsis4))
                .addGap(62, 62, 62))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botonTerminar)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(89, 89, 89))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subsis1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subsis2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subsis3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subsis4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botonTerminar)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subsis1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subsis1ActionPerformed
        // TODO add your handling code here:
        VentanaS1 v = new VentanaS1();
        v.setVisible(true);
    }//GEN-LAST:event_subsis1ActionPerformed

    private void subsis2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subsis2ActionPerformed
        // TODO add your handling code here:
        VentanaS2 window2 = new VentanaS2(); 
        window2.setVisible(true); 
    }//GEN-LAST:event_subsis2ActionPerformed

    private void botonTerminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTerminarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_botonTerminarActionPerformed

    private void subsis3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subsis3ActionPerformed
        // TODO add your handling code here:
        VentanaS3 v = new VentanaS3();
        v.setVisible(true);
    }//GEN-LAST:event_subsis3ActionPerformed

    private void subsis4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subsis4ActionPerformed
        // TODO add your handling code here:
        VentanaS4 v = new VentanaS4();
        v.setVisible(true);
    }//GEN-LAST:event_subsis4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    //javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
                JOptionPane.showMessageDialog(null, "Información acerca del sistema: \n"
                                                  + "- Para que este sistema trabaje correctamente debe estar conectado a la red VPN de la UGR \n  o la base de datos que haya configurado."
                                                  + "\n- Se le mostrarán mensajes de error cuando no introduzca algún dato o éste no sea correcto.\n\n"
                        + "Trabajo realizado por: Alonso Bueno, Manuel Castellón, Pablo Lombardero, Fco. Javier Torres.\n" + "GUI realizada por: Alonso Bueno." );
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonTerminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton subsis1;
    private javax.swing.JButton subsis2;
    private javax.swing.JButton subsis3;
    private javax.swing.JButton subsis4;
    // End of variables declaration//GEN-END:variables
}
