/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazddsi;

import java.sql.SQLException;
import java.util.logging.Level;
import java.time.*; // import the LocalDate class
import java.util.Calendar;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author alonso
 */
public class VentanaS4 extends javax.swing.JFrame {

    /**
     * Creates new form VentanaS4
     */
    public VentanaS4() {
        initComponents();
        this.setTitle("Funcionalidad del subsistema 4");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cajaEdicion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cajaHora = new javax.swing.JTextField();
        cajaFecha = new com.toedter.calendar.JDateChooser();
        botonEjecutarConsulta = new javax.swing.JButton();
        cajaMin = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getStyle() | java.awt.Font.BOLD));
        jLabel1.setText("Funcionalidad 4: Consulta los trabajadores libres");

        jLabel2.setText("Introduzca número de edición:");

        jLabel3.setText("Introduzca la fecha:");

        jLabel4.setText("Introduzca la hora (HH:MM):");

        cajaHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaHoraActionPerformed(evt);
            }
        });

        botonEjecutarConsulta.setText("REALIZAR CONSULTA");
        botonEjecutarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEjecutarConsultaActionPerformed(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText(":");

        jLabel6.setText("NOTA: Sólo se consultan los trabajadores asociados a la edición.");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(150, 150, 150)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cajaEdicion, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cajaFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cajaHora, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cajaMin, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botonEjecutarConsulta)
                .addGap(168, 168, 168))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cajaEdicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cajaFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cajaHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cajaMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonEjecutarConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cajaHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaHoraActionPerformed

    private void botonEjecutarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEjecutarConsultaActionPerformed
        // TODO add your handling code here:
        ConsultasS4 c = new ConsultasS4();
        try {
            c.initialize();
        } catch (Exception ex) {
            Logger.getLogger(VentanaS4.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        // capturar edición de la ventana
        if (cajaEdicion.getText().length() == 0 || cajaHora.getText().length() == 0 || cajaMin.getText().length() == 0)
        {
            JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios. ", "Alerta sobre datos introducidos", JOptionPane.ERROR_MESSAGE);
        }
        else{   // campos NO VACÍOS, ok por ahora ...  
            
            int edicionDada = Integer.parseInt(cajaEdicion.getText());
            int horaDada = Integer.parseInt(cajaHora.getText()) ; 
            int minDados = Integer.parseInt(cajaMin.getText()); 

            if ( !comprobarCampos(edicionDada, horaDada, minDados) ){      // campos ok
                JOptionPane.showMessageDialog(this, "Algún campo no es válido", "Alerta sobre datos introducidos", JOptionPane.ERROR_MESSAGE);
            }
            else{ 
                // campos ok
                int dia  =  cajaFecha.getCalendar().get(Calendar.DAY_OF_MONTH) ; 
                int mes  = (cajaFecha.getCalendar().get(Calendar.MONTH)) + 1 ;
                int anio =  cajaFecha.getCalendar().get(Calendar.YEAR); 

                String cadFechaPreparada = dia + "/" + mes + "/" + anio + " " + horaDada + ":" + cajaMin.getText() + ":" + "00"; 

                System.out.println(cadFechaPreparada);

                // ejecutar la consulta
                String[]  res=  null ;

                try { 
                    res = c.consultaTrabajadoresLibres(edicionDada, cadFechaPreparada);  
                } catch (Exception ex) { 
                    Logger.getLogger(VentanaS4.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(this, "Error al ejecutar la consulta: " + ex.getMessage(), "Operación incorrecta", JOptionPane.ERROR_MESSAGE);
                }

                if (res.length != 0){
                    JOptionPane.showMessageDialog(this, "Trabajadores libres en esa edición: " + imprimeRes(res) , "Notificación de operación realizada", JOptionPane.INFORMATION_MESSAGE);
                }
                else{
                    JOptionPane.showMessageDialog(this, "No hay trabajadores asociados a esta edición." , "Notificación de operación realizada", JOptionPane.INFORMATION_MESSAGE);
                }

            }
        }
        
        try { 
            c.cerrarConexion();
        } catch (SQLException ex) {
            Logger.getLogger(VentanaS4.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonEjecutarConsultaActionPerformed

    private String imprimeRes(String[] res){
        String result = new String(); 
        result += "\n"; 
        int k=1; 
        for(int i=0; i < res.length; i++){
            if(res[i] != null){
                result = result + "  Trabajador " + k + " (DNI): " + res[i] + "\n"; 
                k++; 
            }
        }
        
        return result;
    }
    
    private boolean comprobarCampos (int edicionDada, int horaDada, int minDados)
    {
        boolean ok = true;

        if (edicionDada <0){
            ok = false;
        }
        else{
            if ( !(horaDada >= 0 && horaDada <= 23) ){
                ok=false;
            }
            else {
                if ( !(minDados >= 0 && minDados <= 59 ) ){
                    ok = false; 
                }
            }
        }


        return (ok); 
    }
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEjecutarConsulta;
    private javax.swing.JTextField cajaEdicion;
    private com.toedter.calendar.JDateChooser cajaFecha;
    private javax.swing.JTextField cajaHora;
    private javax.swing.JTextField cajaMin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
