/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazddsi;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author alonso
 */
public class VentanaS2 extends javax.swing.JFrame {

    /**
     * Creates new form VentanaS2
     */
    public VentanaS2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cajaNombre = new javax.swing.JTextField();
        cajaCap = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cajaId = new javax.swing.JTextField();
        botonInsertarPista = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        opcionMenu_deFile = new javax.swing.JMenu();
        opcionAbrir_deFile = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("MENÚ PARA AÑADIR UNA NUEVA PISTA A LA BASE DE DATOS");

        jLabel2.setText("1. Introduzca nombre de la pista:");

        jLabel3.setText("2. Introduzca la capacidad de la pista:");

        cajaNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        cajaCap.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel4.setText("3. Introduzca identificador: ");

        cajaId.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        botonInsertarPista.setText("INSERTAR PISTA");
        botonInsertarPista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInsertarPistaActionPerformed(evt);
            }
        });

        menuFile.setText("File");
        menuFile.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                menuFileAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        opcionMenu_deFile.setText("Activar");
        menuFile.add(opcionMenu_deFile);

        opcionAbrir_deFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        opcionAbrir_deFile.setText("Abrir");
        opcionAbrir_deFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionAbrir_deFileActionPerformed(evt);
            }
        });
        menuFile.add(opcionAbrir_deFile);

        jMenuBar1.add(menuFile);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(botonInsertarPista))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel2))
                                    .addGap(35, 35, 35)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cajaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cajaCap, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(106, 106, 106)
                                    .addComponent(cajaId, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel1)))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cajaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cajaCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cajaId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonInsertarPista, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private boolean comprobarDatosEntrada()
    {
        boolean ok = true; 
        
        if (cajaId.getText().length() == 0 || cajaNombre.getText().length() == 0 || cajaCap.getText().length() == 0)
        {
            ok= false; 
        }
        else
        {
            if ( Integer.parseInt(cajaId.getText()) < 0  )
                ok= false;
            else if ( Integer.parseInt(cajaCap.getText()) <= 0 )
                ok= false;
        }
        
        return ok;
    }
    
    
    private void botonInsertarPistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInsertarPistaActionPerformed
        
        // 1. inicializar la clase encargada de la consulta 
        c = new ConsultasS2();
        try {
            c.initialize();
        } catch (Exception ex) {
            Logger.getLogger(VentanaS2.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        boolean ok = comprobarDatosEntrada();
        
        // 2. ejecutar consulta y ver el resultado 
        if (ok)
        {
            int res=-1; 
            try {
                res = c.insertData( Integer.parseInt(cajaId.getText()), cajaNombre.getText(), Integer.parseInt(cajaCap.getText() ) );
            } catch (Exception ex) {
                Logger.getLogger(VentanaS2.class.getName()).log(Level.SEVERE, null, ex);
            }

            if (res != 0){
                JOptionPane.showMessageDialog(this, "Algo has introducido mal...", "Alerta sobre datos introducidos", JOptionPane.ERROR_MESSAGE);
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Se ha añadido correctamente la pista.\n Código de resultado: "+res , "Notificación de operación realizada", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_botonInsertarPistaActionPerformed

    private void menuFileAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_menuFileAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_menuFileAncestorAdded

    private void opcionAbrir_deFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionAbrir_deFileActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Parece que quieres abrir un archivo", "Alerta sobre prueba", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_opcionAbrir_deFileActionPerformed

    
    ConsultasS2 c; 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonInsertarPista;
    private javax.swing.JTextField cajaCap;
    private javax.swing.JTextField cajaId;
    private javax.swing.JTextField cajaNombre;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenuItem opcionAbrir_deFile;
    private javax.swing.JMenu opcionMenu_deFile;
    // End of variables declaration//GEN-END:variables
}
