/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazddsi;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author alonso
 */
public class VentanaS1 extends javax.swing.JFrame {

    /**
     * Creates new form VentanaS1
     */
    public VentanaS1() {
        initComponents();
        this.setTitle("Funcionalidad del subsistema 1");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cajaEdicion = new javax.swing.JTextField();
        botonConsultar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getStyle() | java.awt.Font.BOLD));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Funcionalidad 1: Consultar dinero total aportado por colaboradores de una edición");
        jLabel1.setAutoscrolls(true);

        jLabel2.setText("Introduzca número de edición:");

        cajaEdicion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaEdicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaEdicionActionPerformed(evt);
            }
        });

        botonConsultar.setText("REALIZAR CONSULTA");
        botonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(90, 90, 90)
                        .addComponent(cajaEdicion, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonConsultar)
                .addGap(248, 248, 248))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cajaEdicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botonConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultarActionPerformed
        // TODO add your handling code here:
        boolean todo_ok = true;
                
        if (cajaEdicion.getText().length() != 0 )
        {
            int numeroEdicion = Integer.parseInt(cajaEdicion.getText());
            if (numeroEdicion < 0)
            {
                todo_ok = false;
                JOptionPane.showMessageDialog(this, "Algo has introducido mal...", "Alerta sobre datos introducidos", JOptionPane.ERROR_MESSAGE);
            }
        }
        else{            
            JOptionPane.showMessageDialog(this, "¡No has introducido el número de edición!", "Alerta sobre datos introducidos", JOptionPane.ERROR_MESSAGE);
            todo_ok=false; 
        }
  
        if (todo_ok){
            ConsultasS1 c = new ConsultasS1();
            try {
                c.initialize();
            } catch (Exception ex) {
                Logger.getLogger(VentanaS1.class.getName()).log(Level.SEVERE, null, ex);
            }

            float totalDineroAportado = -1; 

            try {
                // ejecutar consulta
                totalDineroAportado = c.consultaDineroAportado(Integer.parseInt(cajaEdicion.getText()));
            } catch (Exception ex) {
                Logger.getLogger(VentanaS1.class.getName()).log(Level.SEVERE, null, ex);
            }

            System.out.println("Dinero total aportado: "+ totalDineroAportado );
            JOptionPane.showMessageDialog(null, "Resultado: "+ totalDineroAportado + " €");

        }  
    }//GEN-LAST:event_botonConsultarActionPerformed

    private void cajaEdicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaEdicionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaEdicionActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonConsultar;
    private javax.swing.JTextField cajaEdicion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
